
# CUDA definitions for all CasADi atomic operations
#   Nearly all symbolic, scalar operations are included here.
#   Exhaustive list: https://github.com/casadi/casadi/blob/main/casadi/core/calculus.hpp

from casadi import *

OP_CUDA_DICT = {
    OP_ASSIGN:              "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d];",
    OP_ADD:                 "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] + work[tID + batch_size * %d];",
    OP_SUB:                 "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] - work[tID + batch_size * %d];",
    OP_MUL:                 "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] * work[tID + batch_size * %d];",
    OP_DIV:                 "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] / work[tID + batch_size * %d];",
    OP_NEG:                 "\n        work[tID + batch_size * %d] = -work[tID + batch_size * %d];",
    OP_EXP:                 "\n        work[tID + batch_size * %d] = exp(work[tID + batch_size * %d]);",
    OP_LOG:                 "\n        work[tID + batch_size * %d] = log(work[tID + batch_size * %d]);",
    OP_POW:                 "\n        work[tID + batch_size * %d] = pow(work[tID + batch_size * %d], work[tID + batch_size * %d]);",
    OP_CONSTPOW:            "\n        work[tID + batch_size * %d] = pow(work[tID + batch_size * %d], work[tID + batch_size * %d]);",
    OP_SQRT:                "\n        work[tID + batch_size * %d] = sqrt(work[tID + batch_size * %d]);",
    OP_SQ:                  "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] * work[tID + batch_size * %d];",
    OP_TWICE:               "\n        work[tID + batch_size * %d] = 2.*(work[tID + batch_size * %d]);",
    OP_SIN:                 "\n        work[tID + batch_size * %d] = sin(work[tID + batch_size * %d]);",
    OP_COS:                 "\n        work[tID + batch_size * %d] = cos(work[tID + batch_size * %d]);",
    OP_TAN:                 "\n        work[tID + batch_size * %d] = tan(work[tID + batch_size * %d]);",
    OP_ASIN:                "\n        work[tID + batch_size * %d] = asin(work[tID + batch_size * %d]);",
    OP_ACOS:                "\n        work[tID + batch_size * %d] = acos(work[tID + batch_size * %d]);",
    OP_ATAN:                "\n        work[tID + batch_size * %d] = atan(work[tID + batch_size * %d]);",
    OP_LT:                  "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] < work[tID + batch_size * %d];",
    OP_LE:                  "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] <= work[tID + batch_size * %d];",
    OP_EQ:                  "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] == work[tID + batch_size * %d];",
    OP_NE:                  "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] != work[tID + batch_size * %d];",
    OP_NOT:                 "\n        work[tID + batch_size * %d] = !work[tID + batch_size * %d];",
    OP_AND:                 "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] && work[tID + batch_size * %d];",
    OP_OR:                  "\n        work[tID + batch_size * %d] = work[tID + batch_size * %d] || work[tID + batch_size * %d];",
    OP_FLOOR:               "\n        work[tID + batch_size * %d] = floor(work[tID + batch_size * %d]);",
    OP_CEIL:                "\n        work[tID + batch_size * %d] = ceil(work[tID + batch_size * %d]);",
    OP_FMOD:                "\n        work[tID + batch_size * %d] = fmod(work[tID + batch_size * %d], work[tID + batch_size * %d]);",
    OP_FABS:                "\n        work[tID + batch_size * %d] = fabs(work[tID + batch_size * %d]);",
    OP_SIGN:                "\n        work[tID + batch_size * %d] = sign(work[tID + batch_size * %d]);",
    OP_COPYSIGN:            "\n        work[tID + batch_size * %d] = copysign(work[tID + batch_size * %d], work[tID + batch_size * %d]);",
    OP_IF_ELSE_ZERO:        "\n        work[tID + batch_size * %d] = (work[tID + batch_size * %d] == 0) ? 0 : work[tID + batch_size * %d];",
    OP_ERF:                 "\n        work[tID + batch_size * %d] = erf(work[tID + batch_size * %d]);",
    OP_FMIN:                "\n        work[tID + batch_size * %d] = fmin(work[tID + batch_size * %d], work[tID + batch_size * %d]);",
    OP_FMAX:                "\n        work[tID + batch_size * %d] = fmax(work[tID + batch_size * %d], work[tID + batch_size * %d]);",
    OP_INV:                 "\n        work[tID + batch_size * %d] = 1./(work[tID + batch_size * %d]);",
    OP_SINH:                "\n        work[tID + batch_size * %d] = sinh(work[tID + batch_size * %d]);",
    OP_COSH:                "\n        work[tID + batch_size * %d] = cosh(work[tID + batch_size * %d]);",
    OP_TANH:                "\n        work[tID + batch_size * %d] = tanh(work[tID + batch_size * %d]);",
    OP_ASINH:               "\n        work[tID + batch_size * %d] = asinh(work[tID + batch_size * %d]);",
    OP_ACOSH:               "\n        work[tID + batch_size * %d] = acosh(work[tID + batch_size * %d]);",
    OP_ATANH:               "\n        work[tID + batch_size * %d] = atanh(work[tID + batch_size * %d]);",
    OP_ATAN2:               "\n        work[tID + batch_size * %d] = atan2(work[tID + batch_size * %d], work[tID + batch_size * %d]);",
    OP_CONST:               "\n        work[tID + batch_size * %d] = %.15f;",
    OP_INPUT:               "\n        work[tID + batch_size * %d] = input_%d[tID*nnz_in[%d] + %d];",
    OP_OUTPUT:              "\n        output_%d[tID*nnz_out[%d] + %d] = work[tID + batch_size * %d];",
}

OP_CUDA_DICT_COALESCED = {
    OP_ASSIGN:              "\n        work[tID + %d] = work[tID + %d];",
    OP_ADD:                 "\n        work[tID + %d] = work[tID + %d] + work[tID + %d];",
    OP_SUB:                 "\n        work[tID + %d] = work[tID + %d] - work[tID + %d];",
    OP_MUL:                 "\n        work[tID + %d] = work[tID + %d] * work[tID + %d];",
    OP_DIV:                 "\n        work[tID + %d] = work[tID + %d] / work[tID + %d];",
    OP_NEG:                 "\n        work[tID + %d] = -work[tID + %d];",
    OP_EXP:                 "\n        work[tID + %d] = exp(work[tID + %d]);",
    OP_LOG:                 "\n        work[tID + %d] = log(work[tID + %d]);",
    OP_POW:                 "\n        work[tID + %d] = pow(work[tID + %d], work[tID + %d]);",
    OP_CONSTPOW:            "\n        work[tID + %d] = pow(work[tID + %d], work[tID + %d]);",
    OP_SQRT:                "\n        work[tID + %d] = sqrt(work[tID + %d]);",
    OP_SQ:                  "\n        work[tID + %d] = work[tID + %d] * work[tID + %d];",
    OP_TWICE:               "\n        work[tID + %d] = 2.*(work[tID + %d]);",
    OP_SIN:                 "\n        work[tID + %d] = sin(work[tID + %d]);",
    OP_COS:                 "\n        work[tID + %d] = cos(work[tID + %d]);",
    OP_TAN:                 "\n        work[tID + %d] = tan(work[tID + %d]);",
    OP_ASIN:                "\n        work[tID + %d] = asin(work[tID + %d]);",
    OP_ACOS:                "\n        work[tID + %d] = acos(work[tID + %d]);",
    OP_ATAN:                "\n        work[tID + %d] = atan(work[tID + %d]);",
    OP_LT:                  "\n        work[tID + %d] = work[tID + %d] < work[tID + %d];",
    OP_LE:                  "\n        work[tID + %d] = work[tID + %d] <= work[tID + %d];",
    OP_EQ:                  "\n        work[tID + %d] = work[tID + %d] == work[tID + %d];",
    OP_NE:                  "\n        work[tID + %d] = work[tID + %d] != work[tID + %d];",
    OP_NOT:                 "\n        work[tID + %d] = !work[tID + %d];",
    OP_AND:                 "\n        work[tID + %d] = work[tID + %d] && work[tID + %d];",
    OP_OR:                  "\n        work[tID + %d] = work[tID + %d] || work[tID + %d];",
    OP_FLOOR:               "\n        work[tID + %d] = floor(work[tID + %d]);",
    OP_CEIL:                "\n        work[tID + %d] = ceil(work[tID + %d]);",
    OP_FMOD:                "\n        work[tID + %d] = fmod(work[tID + %d], work[tID + %d]);",
    OP_FABS:                "\n        work[tID + %d] = fabs(work[tID + %d]);",
    OP_SIGN:                "\n        work[tID + %d] = sign(work[tID + %d]);",
    OP_COPYSIGN:            "\n        work[tID + %d] = copysign(work[tID + %d], work[tID + %d]);",
    OP_IF_ELSE_ZERO:        "\n        work[tID + %d] = (work[tID + %d] == 0) ? 0 : work[tID + %d];",
    OP_ERF:                 "\n        work[tID + %d] = erf(work[tID + %d]);",
    OP_FMIN:                "\n        work[tID + %d] = fmin(work[tID + %d], work[tID + %d]);",
    OP_FMAX:                "\n        work[tID + %d] = fmax(work[tID + %d], work[tID + %d]);",
    OP_INV:                 "\n        work[tID + %d] = 1./(work[tID + %d]);",
    OP_SINH:                "\n        work[tID + %d] = sinh(work[tID + %d]);",
    OP_COSH:                "\n        work[tID + %d] = cosh(work[tID + %d]);",
    OP_TANH:                "\n        work[tID + %d] = tanh(work[tID + %d]);",
    OP_ASINH:               "\n        work[tID + %d] = asinh(work[tID + %d]);",
    OP_ACOSH:               "\n        work[tID + %d] = acosh(work[tID + %d]);",
    OP_ATANH:               "\n        work[tID + %d] = atanh(work[tID + %d]);",
    OP_ATAN2:               "\n        work[tID + %d] = atan2(work[tID + %d], work[tID + %d]);",
    OP_CONST:               "\n        work[tID + %d] = %.15f;",
    OP_INPUT:               "\n        work[tID + %d] = input_%d[tID*nnz_in[%d] + %d];",
    OP_OUTPUT:              "\n        output_%d[tID*nnz_out[%d] + %d] = work[tID + %d];",
}